const data = {
"Uncoupled":true,
"Dead End: Paranormal Park":true,
"1899":true,
"Inside Job":true,
"The Bastard Son & The Devil Himself":true,
"Warrior Nun":true,
"The Midnight Club":true,
"Blockbuster":true,
"The Imperfects":true,
"Partner Track":true,
"Fate: The Winx Saga":true,
"Resident Evil":true,
"First Kill":true,
"Q-Force":true,
"The Midnight Gospel":true,
"Space Force":true,
"Raising Dion":true,
"Pretty Smart":true,
"On The Verge":true,
"The Baby-Sitters Club":true,
"Archive 81":true,
"Another Life":true,
"Gentefied":true,
"Cooking With Paris":true,
"Cowboy Bebop":true,
"Hit & Run":true,
"The Crew":true,
"Mr. Iglesias":true,
"Cursed":true,
"Country Comfort":true,
"BONDiNG":true,
"Jupiter's Legacy":true,
"Grand Army":true,
"Dad Stop Embarrassing Me!":true,
"The Irregulars":true,
"Hoops":true,
"The Order":true,
"Teenage Bounty Hunters":true,
"GLOW":true,
"Away":true,
"The Dark Crystal: Age of Resistance":true,
"White Lines":true,
"The Society":true,
"The Expanding Universe of Ashley Garcia":true,
"The Big Show Show":true,
"Patriot Act with Hasan Minhaj":true,
"I Am Not Okay with This":true,
"Altered Carbon":true,
"Greenhouse Academy":true,
"Chilling Adventures of Sabrina":true,
"Astronomy Club: The Sketch Show":true,
"Turn Up Charlie":true,
"Merry Happy Whatever":true,
"V Wars":true,
"October Faction":true,
"Messiah":true,
"AJ and the Queen":true,
"Insatiable":true,
"Spinning Out":true,
"Soundtrack":true,
"Daybreak":true,
"No Good Nick":true,
"The OA":true,
"She's Gotta Have It":true,
"Tuca & Bertie":true,
"Chambers":true,
"Santa Clarita Diet":true,
"One Day At A Time":true,
"Marvel's The Punisher":true,
"Marvel's Jessica Jones":true,
"Friends From College":true,
"Marvel's Daredevil":true,
"The Good Cop":true,
"American Vandal":true,
"Marvel's Iron Fist":true,
"All About the Washingtons":true,
"The Joel McHale Show with Joel McHale":true,
"The Break with Michelle Wolf":true,
"Marvel's Luke Cage":true,
"Seven Seconds":true,
"Everything Sucks!":true,
"Disjointed":true,
"Lady Dynamite":true,
"Haters Back Off":true,
"Chelsea":true,
"Gypsy":true,
"Girlboss":true,
"Sense8":true,
"The Get Down":true,
"Marco Polo":true,
"Bloodline":true,
"Netflix Presents: The Characters":true,
}
